language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: ZpDylCxuD+/NBoXnnqJPnnpPZsihE4W/2/khQNXl7E5ecmV1iBpdxWuYi3gp5oGasuTJt+FbCNZZB2zdLMbEAsUoZzkeHwE7gA1oko1ZFfV4Ti6M9h60NioT+cwJ/5N9JfbdsG3ynw9qo/u6jAQOeN1fmuBfapdsYG6qfba5Ymg8Fu0S6nM0DZiyc3TKnF8m/n70nD0AL/3BVfzVLGkOYgqmakwLm5odBYP2FU4DU1J4alVSS1382YHZr1oEvamiFQ2NdMgVbByWXGxrzqSUfJGsjbVIzNOXcqDewUIRWnGJ9DHkqSkJrn7nsRukQ81sc7NRIote9EOlVCyhNfVGVZsUz9pHVBwgCqh716XY7iTTQL9sOpZhkJEkjUUmbeFeAkdZfeeCe5IA1M4vx/CXmbq8EWlaxS2x+Am2VhQdsHhO2vStkqPPOGcwmjxzXvt7BpPWZ0p/RikCMdD0S2OLe9Y7Y6Q3BCcdXVG1MnHt0BO44IG8X5T2fnfS8vTvxAQsRKAtDbLv/BIx5VhIKcU2PYjeLvlED0u2zK8sg5F6uLiQrd8lPHU24Hqv0II2sUaOw1FDCeRBNTItm390lGrw4z8MZapWqCRGWStIHcAtXrAIQqYGAgsYoxe6igs/6EmAfarNAT8XwgyiKdEjhJQNLiWmLRg1Pm7BYTBmGbvO5J8=
  app: stark-oasis-33588
  on:
    repo: sulfurshade/blog-api
